<?php
/**
 * @var Wordpress2StepVerification $this
 */
?><html>
<head>
    <meta charset="<?php bloginfo('charset'); ?>"/>
    <title><?php _e('Enter verification code', 'wp2sv'); ?></title>

    <style>
        body {
            color: #000000;
        }
        body {
            font-family: arial, sans-serif;
        }
        .body {
            
        }
        
        img {
        	margin-left: 45%;
    		margin-right: 50%;
    		margin-top: 10px;
    		margin-bottom: 20px;
        }
        #verify-form {
            margin: auto;
            width: 25%;
            border: 3px solid #F7F7F7;
    		padding: 10px;
    		background-color: #F7F7F7;
            box-shadow: 0px 5px 0px #1276CC;
        }
        div.text {
            padding-bottom: 1em;
            padding-right: 1em;
        }
        div.error {
            color: white;
            padding-right: 1em;
            background-color: rgba(255, 0, 0, 0.54);
    		margin-top: 5px;
    		padding: 5px;
    		width: auto;
        }
        .smaller {
            font-size: smaller;
        }
        #pinlabel {
            font-size: 0.8em;
            font-weight: bold;
        }
        #persistent-container {
            padding-left: 75px;
        }
        .padded {
            margin-top: 3px;
        }
    </style>
    <?php wp_print_scripts('jquery'); ?>
    <script type="text/javascript">
        function emailCode(user_email) {
            var type=user_email?'user_email':'email';
            jQuery('#type').val(type);
            jQuery("#smsUserPin").val('');
            jQuery("#action").val('send-email');
            jQuery('#verify-form').submit();
            return false;
        }
        function enterBackupCode() {
            jQuery('#type').val('backup-codes');
            jQuery("#smsUserPin").val('');
            jQuery("#action").val('backup-codes');
            jQuery('#verify-form').submit();
            return false;
        }
        function usePhone() {
            jQuery('#type').val('phone');
            jQuery("#smsUserPin").val('');
            jQuery('#verify-form').submit();
            return false;
        }
        function cancel() {
            jQuery("#action").val('cancel');
            jQuery('#verify-form').submit();
            return false;
        }
    </script>
</head>
<body>

<img src="https://s3-us-west-1.amazonaws.com/dsuploads/wp-content/uploads/2016/04/15121631/2-step-auth-lock.png" align="middle">
<div class="body">
    <form name="verifyForm" method="post" action="" id="verify-form">
        <input type="hidden" name="wp2sv_nonce" value="<?php echo wp_create_nonce('wp2sv_nonce'); ?>"/>
        <input type="hidden" name="wp2sv_type" id="type" value="<?php echo $this->get_receive_method(); ?>"/>
        <input type="hidden" name="wp2sv_action" id="action" value="check-code"/>
        <br/>
        <div class="text smaller" id="verifyText">
            <?php
            $max_code_length = 6;
            if ($this->get_receive_method() == 'mobile') {
                _e('Enter the verification code generated by your mobile application.', 'wp2sv');
            } elseif (in_array($this->get_receive_method(),array('email','user_email'))) {
                printf(__('Enter the verification code sent to your email ending in %s.', 'wp2sv'), $this->get_email_ending());
            } elseif ($this->get_receive_method() == 'backup-codes') {
                $max_code_length = 8;
                _e('Enter your backup code','wp2sv');
            }
            ?>
        </div>
        <div id="verify">
            <div>
                <label for="smsUserPin" id="pinlabel">
                    <?php _e('Enter code:', 'wp2sv'); ?>
                </label>
                <input type="text" title="Verification codes contain only numbers." pattern="[0-9 ]*" dir="ltr"
                       autocomplete="off" size="<?= $max_code_length; ?>" value="" id="smsUserPin" name="wp2sv_code">
                <input type="submit" class="sa-button" value="<?php _e('Verify', 'wp2sv'); ?>" id="smsVerifyPin"
                       name="smsVerifyPin">
            </div>
            <?php if ($this->error_message): ?>
                <div class="error smaller" id="error">
                    <?php echo $this->error_message; ?>
                </div>
            <?php endif; ?>

            <div class="padded" id="persistent-container">
                <input type="checkbox"<?php checked(true, $this->wp2sv_user_fav_trusted()) ?> value="yes"
                       id="PersistentCookie" name="wp2sv_remember">
                <label for="PersistentCookie" class="smaller">
                    <?php _e('Remember this computer for 30 days.', 'wp2sv'); ?>
                </label>
            </div>
            <br/>
            <?php if ($this->get_receive_method() != 'mobile') { ?>
                <div class="padded smaller" id="cancelLink">
                    <a href="javascript:usePhone()"><?php _e('Use your phone', 'wp2sv'); ?></a>
                </div>
            <?php } ?>
            <?php if ($this->has_email()): ?>
                <div class="padded smaller" id="didnotreceive">
                    <a href="javascript:emailCode()">
                        <?php
                        if ($this->get_receive_method() == 'email') {
                            _e('Didn\'t receive email? - Send code again', 'wp2sv');
                        } else {
                            _e('Don\'t have your phone? - Send code to your email', 'wp2sv');
                        }
                        ?>
                    </a></div>
            <?php endif; ?>
            <?php if ($this->get_receive_method() != 'backup-codes') { ?>
                <div class="padded smaller" id="cancelLink">
                    <a href="javascript:enterBackupCode()"><?php _e('Use backup code', 'wp2sv'); ?></a>
                </div>
            <?php } ?>
            <?php
            $user_email=wp_get_current_user()->user_email;
            if(empty($this->wp2sv_email)){ //Use account's email if user doesn't set one
                ?>
                <div class="padded smaller">
                    <a href="javascript:emailCode(1)">
                        <?php
                        if ($this->get_receive_method() == 'user_email') {
                            _e('Didn\'t receive email? - Send code again', 'wp2sv');
                        } else {
                            _e('Send code to user email', 'wp2sv');
                        }
                        ?>
                        </a>
                </div>
            <?php }?>
            <div class="padded smaller" id="cancelLink">
                <a href="javascript:cancel()"><?php _e('Cancel', 'wp2sv'); ?></a>
            </div>
        </div>
    </form>
    <div id="filter" style="display: none;"></div>
    <div style="clear:both"></div>
</div>
</body>
</html>